### ISSUE TITLE
[bug] status lang check

### ISSUE THREAD

**Issue by gzezFISHER** [segment-oj/segmentoj#92]
https://github.com/segment-oj/segmentoj/blob/8440fda8f94175a0a3d98f7dd2e238edb86a3671/status/views.py#L41

```python
if 1 <= data['lang'] <= 10:
    return Response({
        'code': 4001,
        'detail': 'Unknow language',
    })
```

???

**Comment by szdytom** [comment]
fixed via 681f445919d7edab282e0ff534a36dc29b506a12
